k apply -f backend-feed-deployment.yaml
k apply -f backend-feed-deployment.yaml
k apply -f backend-feed-service.yaml
k apply -f backend-user-deployment.yaml
k apply -f backend-user-service.yaml
k apply -f frontend-deployment.yaml
k apply -f frontend-service.yaml
k apply -f reverseproxy-deployment.yaml
k apply -f reverseproxy-service.yaml